### ISSUE TITLE
Feature request- change multiple bookmarks

### ISSUE THREAD

**Issue by piecevcake** [rafaelgssa/container-bookmarks#1]
Would be helpful!

**Comment by mrwensveen** [comment]
I usually collect bookmarks that should be opened in the same container in a folder. Would it be possible to set the container for the bookmarks in a folder on the folder level?

Another option could be to use the bookmarks' tags to configure the container it should open in, in stead of a hash on the url. This would make it easier to change multiple bookmarks because the bookmark manager already allows you to edit the tags of multiple bookmarks. This would also make the "Edit Container Bookmark" dialog somewhat optional (though still useful).

**Comment by rafaelgssa** [comment]
v1.1.0 allows you to change the container of all bookmarks in a folder. I hope this helps.

@mrwensveen It has to be the URL, as far as I know, otherwise it wouldn't work. But what tags are you talking about?

**Comment by mrwensveen** [comment]
The tags that are stored in the bookmark, which can be added using the
native bookmark dialogs.
I'll add a screenshot later.

**Comment by rafaelgssa** [comment]
The tags aren't available through the API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/BookmarkTreeNode

And there isn't a "onClicked" event for bookmarks: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks So we can't know which bookmark was clicked.
